// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nikhilnarayanan623/x-tention-crew/service2/pkg/api"
	"github.com/nikhilnarayanan623/x-tention-crew/service2/pkg/api/handler"
	"github.com/nikhilnarayanan623/x-tention-crew/service2/pkg/client"
	"github.com/nikhilnarayanan623/x-tention-crew/service2/pkg/config"
	"github.com/nikhilnarayanan623/x-tention-crew/service2/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	userServiceClient, err := client.NewUserServiceClient(cfg)
	if err != nil {
		return nil, err
	}
	useCase := usecase.NewUseCase(userServiceClient)
	serviceHandler := handler.NewHandler(useCase)
	server, err := api.NewServer(cfg, serviceHandler)
	if err != nil {
		return nil, err
	}
	return server, nil
}
