// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nikhilnarayanan623/x-tention-crew/user-servcie/pkg/api"
	"github.com/nikhilnarayanan623/x-tention-crew/user-servcie/pkg/api/handler"
	"github.com/nikhilnarayanan623/x-tention-crew/user-servcie/pkg/api/service"
	"github.com/nikhilnarayanan623/x-tention-crew/user-servcie/pkg/config"
	"github.com/nikhilnarayanan623/x-tention-crew/user-servcie/pkg/db"
	"github.com/nikhilnarayanan623/x-tention-crew/user-servcie/pkg/repository"
	"github.com/nikhilnarayanan623/x-tention-crew/user-servcie/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	gormDB, err := db.ConnectToDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepo := repository.NewUserRepo(gormDB)
	cacheRepo := repository.NewCacheRepo(cfg)
	userUseCase := usecase.NewAuthUseCase(userRepo, cacheRepo)
	userServiceServer := service.NewUserService(userUseCase)
	userHandler := handler.NewUserHandler(userUseCase)
	server, err := api.NewServer(cfg, userServiceServer, userHandler)
	if err != nil {
		return nil, err
	}
	return server, nil
}
